version: "3.7"

services:
  aerospike:
    image: aerospike/aerospike-server
    restart: always
    volumes:
      - ./:/workspace
    command: [ "--config-file","/workspace/aerospike.conf"]
    ports:
      - "3000:3000" # Client connections
      - "3001:3001" # Mesh heartbeats
      - "3002:3002" # Fabric
      - "3003:3003" # Info

  vscode:
    build: .
    volumes:
      - ./:/workspace
      # Docker
      - ~/.docker:/root/.docker:z
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory for Linux, OSX and WSL
      # On Linux and OSX, a symlink /mnt/ssh <-> ~/.ssh is
      # created in the container. On Windows, files are copied
      # from /mnt/ssh to ~/.ssh to fix permissions.
      - ~/.ssh:/mnt/ssh
      # Shell history persistence
      - ~/.zsh_history:/root/.zsh_history:z
      # Git config
      - ~/.gitconfig:/root/.gitconfig:z
      # Kubernetes
      - ~/.kube:/root/.kube:z
    environment:
      - TZ=Armenia/Yerevan
    cap_add:
      # For debugging with dlv
      - SYS_PTRACE
    security_opt:
      # For debugging with dlv
      - seccomp:unconfined
    entrypoint: [ "zsh", "-c", "while sleep 1000; do :; done" ]
    links:
      - aerospike