# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint version
          golangci-lint run

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Start db and migrate
        run: |
          docker-compose up -d db
          docker-compose up migrate
      - name: Test
        run: CONFIG_PATH=test/ci.yml go test -v ./...

      - name: Run coverage
        run: CONFIG_PATH=test/ci.yml go test -race -coverprofile=coverage.out -covermode=atomic ./... -coverpkg=./...``

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"


      - name: Build
        run: go build -v ./...
