# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres_test:
        image: postgres:latest

        env:
          POSTGRES_USER: local
          POSTGRES_PASSWORD: local_pwd
          POSTGRES_DB: local
          POSTGRES_PORT: 5432

        volumes:
          - ./sql/:/docker-entrypoint-initdb.d

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: CONFIG_PATH=test/config.yml go test -v ./...

      - name: Run coverage
        run: CONFIG_PATH=test/config.yml go test -race -coverprofile=coverage.out -covermode=atomic ./... -coverpkg=./...``

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
